{{- if .Values.chaincode.enabled }}
{{- if .Values.chaincode.sourceFrom.enabled }}
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fabric-deploy-flow.fullname" . }}-chaincode-source-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: {{ .Values.chaincode.sourceFrom.storageClass }}
  resources:
    requests:
      storage: {{ .Values.chaincode.sourceFrom.size }}
{{- end }}
{{- end }}