{{- range $i, $ordererOrg := .Values.consortium.ordererOrgs }}
{{- range $j, $node := $ordererOrg.nodes }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $node }}-{{ $ordererOrg.name }}-orderer-env
  namespace: {{ $ordererOrg.name }}
data:
  FABRIC_LOGGING_SPEC: "DEBUG"
  ORDERER_GENERAL_LISTENADDRESS: "0.0.0.0"
  ORDERER_GENERAL_GENESISMETHOD: "file"
  ORDERER_GENERAL_GENESISFILE: "/var/hyperledger/orderer/genesis.block"
  ORDERER_GENERAL_LOCALMSPID: {{ $ordererOrg.id }}
  ORDERER_GENERAL_LOCALMSPDIR: "/var/hyperledger/orderer/msp"
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_PRIVATEKEY: "/var/hyperledger/orderer/tls/pair/tls.key"
  ORDERER_GENERAL_TLS_CERTIFICATE: "/var/hyperledger/orderer/tls/pair/tls.crt"
  ORDERER_GENERAL_TLS_ROOTCAS: "/var/hyperledger/orderer/tls/tlscacert.pem"

  # etcdraft
  {{- if eq $.Values.consortium.ordererType "etcdraft" }} 
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: "/var/hyperledger/orderer/tls/pair/server.crt"
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: "/var/hyperledger/orderer/tls/pair/server.key"
  ORDERER_GENERAL_CLUSTER_ROOTCAS: "/var/hyperledger/orderer/tls/tlscacert.pem"
  {{- end }}
{{- end }}
{{- end }}