{{- $deployName := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- $chartVersion := .Chart.AppVersion }}
{{- $releaseName := .Release.Name }}
{{- $labels := include "fabric-deploy-flow.labels" . }}

{{- range $i, $peerOrg := .Values.consortium.peerOrgs }}
{{- range $j, $node := $peerOrg.nodes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $node }}-{{ $peerOrg.name }}-peer
  namespace: {{ $peerOrg.name }}
  labels:
{{ $labels | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $node }}-{{ $peerOrg.name }}
      app.kubernetes.io/instance: {{ $node }}-{{ $peerOrg.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $node }}-{{ $peerOrg.name }}
        app.kubernetes.io/instance: {{ $node }}-{{ $peerOrg.name }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: id-cert
          secret:
            secretName: {{ $node }}-{{ $peerOrg.name }}-peer-idcert
        - name: id-key
          secret:
            secretName: {{ $node }}-{{ $peerOrg.name }}-peer-idkey
        - name: ca-cert
          secret:
            secretName: admin-{{ $peerOrg.name }}-admin-cacert
        - name: tlsca-cert
          secret:
            secretName: admin-{{ $peerOrg.name }}-admin-tlscacert
        - name: admin-cert
          secret:
            secretName: admin-{{ $peerOrg.name }}-admin-idcert
        - name: tls-pair
          secret:
            secretName: {{ $node }}-{{ $peerOrg.name }}-peer-tlspair
        - name: config
          configMap: 
            name: {{ $peerOrg.name }}-nodeous-config
        {{- if $.Values.dependencies.docker.sock }}
        - name: docker-sock
          hostPath:
            path: {{ $.Values.dependencies.docker.sock }}
        {{- end }}
      containers:
        - name: {{ $node }}-{{ $peerOrg.name }}-entry
          image: "{{ $.Values.consortium.repo }}/fabric-peer:{{ $.Values.consortium.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 7051
              protocol: TCP
            - name: event
              containerPort: 7053
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ $node }}-{{ $peerOrg.name }}-peer-env
          volumeMounts:
            - name: ca-cert
              mountPath: /etc/hyperledger/fabric/peer/msp/cacerts
            - name: tlsca-cert 
              mountPath: /etc/hyperledger/fabric/peer/msp/tlscacerts
            - name: admin-cert 
              mountPath: /etc/hyperledger/fabric/peer/msp/admincerts
            - name: id-cert
              mountPath: /etc/hyperledger/fabric/peer/msp/signcerts
            - name: id-key 
              mountPath: /etc/hyperledger/fabric/peer/msp/keystore
            - name: tlsca-cert 
              mountPath: /etc/hyperledger/fabric/tls
            - name: tls-pair
              mountPath: /etc/hyperledger/fabric/tls/pair
            - name: config
              mountPath: /etc/hyperledger/fabric/peer/msp
            {{- if $.Values.dependencies.docker.sock }}
            - name: docker-sock
              mountPath: /host/var/run/docker.sock
            {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $peerOrg.name }}-nodeous-config
  namespace: {{ $peerOrg.name }}
data: 
  config.yaml: |
    NodeOUs:
      Enable: true
      ClientOUIdentifier:
        Certificate: cacerts/cacert.pem
        OrganizationalUnitIdentifier: client
      PeerOUIdentifier:
        Certificate: cacerts/cacert.pem
        OrganizationalUnitIdentifier: peer
{{- end }}