{{- if .Values.consortium.useAdvance }}
{{- if .Values.advanced.couchdb.enabled }}
{{- range $i, $org := .Values.consortium.peerOrgs }}
{{- range $j, $node := $org.nodes }}
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: {{ $node }}-{{ $org.name }}-couchdb
  namespace: {{ $org.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $node }}-{{ $org.name }}-couchdb
      app.kubernetes.io/instance: {{ $node }}-{{ $org.name }}-couchdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $node }}-{{ $org.name }}-couchdb
        app.kubernetes.io/instance: {{ $node }}-{{ $org.name }}-couchdb
    spec:
      volumes:
      {{- if $.Values.advanced.persistence.enabled }}
        - name: data-persistent
          persistentVolumeClaim:
            claimName: couchdb-pvc
      {{- end }}
      containers:
        - name: {{ $node }}-{{ $org.name }}-couchdb
          image: {{ $.Values.advanced.couchdb.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 5984
              protocol: TCP 
          env:
            - name: COUCHDB_USERNAME
              value: {{ $.Values.advanced.couchdb.username }}
            - name: COUCHDB_PASSWORD
              value: {{ $.Values.advanced.couchdb.password }} 
          {{- if $.Values.advanced.persistence.enabled }}
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: data-persistent
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}