{{- if .Values.consortium.useAdvanced }}
{{- if .Values.advanced.couchdb.enabled }}
{{- range $i, $org := .Values.consortium.peerOrgs }}
{{- range $j, $node := $org.nodes }}
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: {{ $node }}-{{ $org.name }}-couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $node }}-{{ $org.name }}-couchdb
      app.kubernetes.io/instance: {{ $node }}-{{ $org.name }}-couchdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $node }}-{{ $org.name }}-couchdb
        app.kubernetes.io/instance: {{ $node }}-{{ $org.name }}-couchdb
    spec:
      volumes:
      {{- if .Values.advanced.persistence.enabled }}
        - name: data-persistent
          persistentVolumeClaim:
            claimName: couchdb-pvc
      {{- end }}
      containers:
        - name: {{ $node }}-{{ $org.name }}-couchdb
          image: {{ .Values.couchdb.image }}:{{ .Values.couchdb.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 5094
              protocol: TCP 
          env:
            - name: COUCHDB_USERNAME
              value: ""
            - name: COUCHDB_PASSWORD
              value: "" 
          volumeMounts:
          {{- if .Values.couchdb.persistence.enabled }}
            - mountPath: /opt/couchdb/data
              name: data-persistent
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}