# Default values for fabric-deploy-flow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

dependencies:
  kubeConfig: # k8s主机的配置文件，下面只能选择一种
    localHost: "/root/.kube"  # 本地映射  
    secret: ""  # secret 存储（建议）
  tools:
    image: fabric-utils:1.0.3  # 依赖的镜像
  docker:
    sock: "/var/run/docker.sock"  # 确认主机的文件目录，对链码安装实例化有用

consortium:
  recreated: true  
  name: sample
  ordererType: solo # 不支持kafka，只有solo和etcdraft
  repo: "hyperledger"
  tag: 1.4.2
  affiliation: "svc.cluster.local" # 固定
  ordererOrgs: 
    - name: orderer
      id: OrdererMSP
      caserver: http://admin:adminpw@org1-ca-server.default.svc.cluster.local:7054
      nodes: ["orderer"]
  peerOrgs:
    - name: org1
      id: Org1MSP
      caserver: http://admin:adminpw@org1-ca-server.default.svc.cluster.local:7054 
      nodes: ["peer0","peer1"]
    - name: org2
      id: Org2MSP
      caserver: http://admin:adminpw@org1-ca-server.default.svc.cluster.local:7054 
      nodes: ["peer0"]

# 通道创建 
channel:
  enabled: true  
  name: "mychannel"

# 链码安装与启动
chaincode:
  enabled: false 
  channel: ""
  name: ""
  version: ""
  path: ""
  args: ""
  policy: ""
  sourceFrom: # 链码存储；建议nfs
    enabled: true 
    size: 1Gi
    storageClass: ""

# 是否启动explorer,暂无
explorer:
  enabled: false 
  image: ""
  ingress:
    enabled: false  
    tls: ""

# 清理
cleanup:
  enabled: true 

nodeSelector: {}

tolerations: []

affinity: {}
